SUPABASE_URL = "https://eznurueupgcdoglezpkr.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bnVydWV1cGdjZG9nbGV6cGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1NjMzNjgsImV4cCI6MjEwMTEzOTM2OH0.bUdQWcvfze72bCKRf4gchr6p8uRBWHkrYL04Kdak90c"





